dist: xenial
language: python
sudo: required

addons:
  apt:
    packages:
      - vim

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7

install:
  - pip install flake8 mock pytest
  - mkdir -p ~/.vim && cp -r plugin ~/.vim/

script:
  - flake8 plugin/ tests/
  - PYTHONPATH="$(pwd)/plugin:$PYTHONPATH" pytest -s -v tests/
  - vim -c ":call PostToXsnippet()" plugin/xsnippet.vim

notifications:
  email: false
